# Generated by Django 4.0.3 on 2022-03-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('content', models.TextField(max_length=255, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создание')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='картинки')),
                ('is_publisher', models.BooleanField(default=True, verbose_name='публикация')),
            ],
        ),
    ]
